# Generated by Django 2.2 on 2020-12-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(null=True, upload_to='group/cover/')),
                ('user_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(null=True, upload_to='group/profile/')),
                ('user_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
            ],
        ),
    ]
