# Generated by Django 2.2 on 2020-12-28 07:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chanel', '0003_auto_20201227_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='channel/thumbnail/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chanel.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='channel/thumbnail/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chanel.Channel')),
            ],
        ),
    ]
