# Generated by Django 2.2 on 2020-12-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanel', '0004_channelcover_channelthumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelthumbnail',
            old_name='cover',
            new_name='thumbnail',
        ),
    ]
