# Generated by Django 2.2 on 2020-12-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, null=True)),
                ('sidebar', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
