# Generated by Django 2.2 on 2020-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='post',
            field=models.TextField(blank=True, help_text='Appears in posts are loaded', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='footer',
            field=models.TextField(blank=True, help_text='Appears on the bottom of home footer', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='header',
            field=models.TextField(blank=True, help_text='Appears on all pages right under the nav bar', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='sidebar',
            field=models.TextField(blank=True, help_text='Appears on the bottom of home sidebar', null=True),
        ),
    ]
