# Generated by Django 2.2 on 2020-12-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_campaign_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
