# Generated by Django 2.2 on 2020-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_auto_20201229_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
