# Generated by Django 2.2 on 2020-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_auto_20201229_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='campaign/'),
        ),
    ]
