# Generated by Django 2.2 on 2020-12-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_auto_20201229_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
