# Generated by Django 2.2 on 2020-12-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Private')], default=1, max_length=5),
        ),
    ]
