# Generated by Django 2.2 on 2020-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
