# Generated by Django 2.2 on 2020-12-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='sperated by a comma (,)', null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactivate')], default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AutoGroupJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='sperated by a comma (,)', null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactivate')], default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AutoPageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='sperated by a comma (,)', null=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Deactivate')], default=1, max_length=5)),
            ],
        ),
    ]
