# Generated by Django 2.2 on 2020-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofriend',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autogroupjoin',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autopagelike',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
