# Generated by Django 2.2 on 2020-12-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20201226_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autofriend',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='autogroupjoin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='autogroupjoin',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='autopagelike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='autopagelike',
            name='user_name',
        ),
        migrations.AddField(
            model_name='autogroupjoin',
            name='group',
            field=models.TextField(blank=True, help_text='group name(s), sperated by a comma (,)', null=True),
        ),
        migrations.AddField(
            model_name='autopagelike',
            name='page',
            field=models.TextField(blank=True, help_text='page name(s), sperated by a comma (,)', null=True),
        ),
        migrations.AlterField(
            model_name='autofriend',
            name='user',
            field=models.TextField(blank=True, help_text='user name(s), sperated by a comma (,)', null=True),
        ),
    ]
